#! /usr/bin/env python3

import argparse, re, sys

CITEKEY_RE = re.compile("(?<={).*(?=,)")

parser = argparse.ArgumentParser(description="Print unused cite keys")
parser.add_argument('bibfile')
parser.add_argument('txtfile')
args = parser.parse_args()

## Get list of cite keys from bibfile.

with open(args.bibfile, 'r') as bibfile:
    lines = bibfile.readlines()
lines = filter(lambda l: '@' in l, lines)
matches = map(lambda l: CITEKEY_RE.search(l), lines)
matches = filter(lambda m: m is not None, matches)
citekeys = map(lambda m: m.group(0), matches)
citekeys = list(citekeys)

print(f"> Found {len(citekeys)} cite keys in {args.bibfile}.", file=sys.stderr)

## Get full text of the txtfile

with open(args.txtfile, 'r') as txtfile:
    contents = txtfile.read()
citekeys_unused = filter(lambda c: c not in contents, citekeys)
citekeys_unused = list(citekeys_unused)

print(
    f"> Of those, {len(citekeys_unused)} are not used in {args.txtfile}.",
    file=sys.stderr)
[print(c) for c in citekeys_unused]
